version: '3.7'
services:
  moi-database:
    image: mysql:5.7
    container_name: moi-db-compose
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  moi-app:
    build: .
    image: moi-project
    container_name: moi-app-compose
    ports:
      - "${APP_PORT}:9091"
    depends_on: 
      - moi-database
    restart: on-failure
